AWSTemplateFormatVersion: 2010-09-09

Description: test S3 template

Resources:
  TestStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'test-store-s3-rnd-rkzel'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      AccessControl: Private
      LoggingConfiguration:
        DestinationBucketName: "arn:aws:s3:::main-logging-bucket-rnd"
        LogFilePrefix: testing-logs

  DenyInsecureAccessPolicy:
    Type: AWS::S3::BucketPolicy 
    Properties:
      Bucket: !Ref TestStore
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Resource: !Join
             - ''
             - - 'arn:aws:s3:::'
               - !Ref TestStore
               - /*
            Principal: "*"
            Action: "*"
            Condition:
              Bool:
                "aws:SecureTransport": false

