AWSTemplateFormatVersion: 2010-09-09

Description: test S3 template

Mappings:
  RegionalLoggingBucket:
    eu-west-1:
      Name: main-logging-bucket-rnd
    eu-west-2:
      Name: main-logging-bucket-rnd-london

Resources:
  TestStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      AccessControl: Private
      LoggingConfiguration:
        DestinationBucketName: !FindInMap [RegionalLoggingBucket, !Ref "AWS::Region", Name]
        LogFilePrefix: rnd-logs-3

  DenyInsecureAccessPolicy:
    Type: AWS::S3::BucketPolicy 
    Properties:
      Bucket: !Ref TestStore
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Resource: !Join
             - ''
             - - 'arn:aws:s3:::'
               - !Ref TestStore
               - /*
            Principal: "*"
            Action: "*"
            Condition:
              Bool:
                "aws:SecureTransport": false

