AWSTemplateFormatVersion: 2010-09-09

Description: test S3 template

Resources:
  TestStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'test-store-s3-rnd-rkzel'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True


